import Head from "next/head";
import ContactBgImage from "../../components/contact/contact-bg-image";
import ContactForm from "../../components/contact/contact-form";
import ContactLocation from "../../components/contact/contact-location";
import Footer from "../../components/layouts/footer";

const ContactPage = () => {
    return (
      <>
        <Head>
          <title className="">Shipping Tracking-Contact</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <ContactBgImage />
        <ContactLocation />
        <ContactForm />
        <Footer />
      </>
    );
}

export default ContactPage