import Head from "next/head";
import HelpBgImage from "../../components/help/help-bg-image";
import Faq, { howToTrack } from "../../components/layouts/faq";
import Footer from "../../components/layouts/footer";

const imgMobile = (
  <div className="md:hidden flex justify-center items-center">
    <img src="/images/cars.jpg" alt="" width={250} height={150} />
  </div>
);

const HelpPage = () => {
    return (
      <>
        <Head>
          <title className="">Shipping Tracking-Help</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <HelpBgImage />
        <Faq faqHeader={imgMobile} how={howToTrack} />
        <Footer />
      </>
    );
}

export default HelpPage