import Head from "next/head";
import Login from "../../components/auth/login";

const LoginPage = () => {
  return (
    <>
      <Head>
        <title className="">Login page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </>
  );
};

export default LoginPage;
