import Head from "next/head";
import ResetEmail from "../../components/auth/reset-email";

const Email = () => {

     return (
       <>
         <Head>
           <title className="">Forget Email</title>
           <meta name="description" content="Generated by create next app" />
           <meta
             name="viewport"
             content="width=device-width, initial-scale=1"
           />
           <link rel="icon" href="/favicon.ico" />
         </Head>

         <ResetEmail />
       </>
     );
}

export default Email