import Head from "next/head";
import ResetPassword from "../../components/auth/reset-password";

const Password = () => {

  return (
    <>
      <Head>
        <title className="">Forget Password</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ResetPassword />
    </>
  );
};

export default Password;
