import Head from "next/head";
import SignUp from "../../components/auth/sign-up";

const SignUpPage = () => {
    return (
    <>
      <Head>
        <title className="">Sign up page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignUp />
    </>
  );
};

export default SignUpPage